/*
 * mod-solo-loot-reroll
 *
 * Smart creature-loot rerolling for AzerothCore Playerbot:
 * - active with one OR several real online players;
 * - for each creature loot, one non-ignored real player is selected at random;
 * - armor defaults to the highest armor proficiency the player currently has;
 * - weapons are filtered with Player::CanUseItem;
 * - an unusable/wrong armor or weapon first tries to reroll into another usable
 *   item of the SAME quality from the same creature loot pool;
 * - if no same-quality replacement exists, the original item stays and the
 *   highest lower-quality compatible item available can be added as a bonus.
 *
 * No custom SQL tables are created. The module only READS AzerothCore's
 * existing creature/reference loot tables and conditions table.
 */

#include "Chat.h"
#include "Config.h"
#include "DatabaseEnv.h"
#include "Group.h"
#include "ItemTemplate.h"
#include "Log.h"
#include "LootMgr.h"
#include "ObjectMgr.h"
#include "Player.h"
#include "ScriptMgr.h"
#include "SharedDefines.h"
#include "Util.h"
#include "WorldSession.h"

#include <algorithm>
#include <atomic>
#include <cctype>
#include <cstdint>
#include <memory>
#include <mutex>
#include <string>
#include <stdexcept>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <deque>

using namespace Acore::ChatCommands;

namespace SoloLootReroll
{
enum class ArmorPreference : uint8
{
    Auto = 0,
    Cloth,
    Leather,
    Mail,
    Plate,
    Off
};

enum class GearCategory : uint8
{
    None = 0,
    Armor,
    Weapon
};

struct ConfigData
{
    bool Enable = true;
    bool EnableArmor = true;
    bool EnableWeapons = true;
    uint32 MinQuality = ITEM_QUALITY_UNCOMMON;

    // Conservative anti-farming defaults:
    // greens may be replaced by another green, rare+ are kept.
    bool ReplaceUncommon = true;
    bool ReplaceRareOrHigher = true;

    // If no usable same-quality replacement exists, keep the original item and
    // add the highest lower-quality compatible item available in the same pool.
    bool LowerQualityFallbackBonus = true;

    // Player feedback / undo history.
    bool NotifySubstitutions = true;
    uint32 MaxUndoRecordsPerCharacter = 100;

    bool Debug = false;
};

struct Candidate
{
    uint32 ItemId = 0;
    float Weight = 1.0f;
    uint16 EffectiveLootMode = LOOT_MODE_DEFAULT;
    uint8 GroupId = 0;
    uint8 MinCount = 1;
    uint8 MaxCount = 1;
};


enum class SubstitutionKind : uint8
{
    Replacement = 0,
    Bonus = 1
};

struct SubstitutionRecord
{
    uint32 Id = 0;
    uint64 PlayerGuid = 0;
    SubstitutionKind Kind = SubstitutionKind::Replacement;

    // Original drop generated by AzerothCore.
    uint32 OriginalItemId = 0;
    int32 OriginalRandomPropertyId = 0;

    // Item inserted by the module.
    uint32 SubstituteItemId = 0;

    bool Undone = false;
};


static ConfigData g_Config;

// Character preferences are intentionally session-only.
// Auto is the default, therefore no persistence/custom SQL table is needed.
static std::unordered_map<uint64, ArmorPreference> g_Preferences;
static std::mutex g_PreferencesMutex;

// Players can opt out of being selected as the smart-loot target.
// Session-only: no custom SQL table is required.
static std::unordered_set<uint64> g_IgnoredLootPlayers;
static std::mutex g_IgnoredLootPlayersMutex;

static std::atomic<uint32> g_NextSubstitutionId{1};
static std::unordered_map<uint64, std::deque<SubstitutionRecord>> g_SubstitutionHistory;
static std::mutex g_SubstitutionMutex;

// Loot caches are built lazily from the existing World DB.
static std::unordered_map<uint32, std::shared_ptr<std::vector<Candidate>>> g_PoolCache;
static std::unordered_map<LootTemplate const*, uint32> g_TemplateToCreatureLootId;
static bool g_TemplateMapBuilt = false;
static std::mutex g_CacheMutex;

static bool IsPlayerBot(Player const* player)
{
    if (!player)
        return false;

    WorldSession const* session = player->GetSession();

    // This is a native flag in the Playerbot fork's WorldSession and is set
    // for PlayerBot sessions. It avoids account-name / character-name guesses.
    return session && session->IsBot();
}

static uint64 PreferenceKey(Player const* player)
{
    return player ? player->GetGUID().GetRawValue() : 0;
}

static bool IsLootIgnored(Player const* player)
{
    if (!player)
        return true;

    std::lock_guard<std::mutex> lock(g_IgnoredLootPlayersMutex);
    return g_IgnoredLootPlayers.count(PreferenceKey(player)) != 0;
}

static void SetLootIgnored(Player const* player, bool ignored)
{
    if (!player)
        return;

    std::lock_guard<std::mutex> lock(g_IgnoredLootPlayersMutex);

    if (ignored)
        g_IgnoredLootPlayers.insert(PreferenceKey(player));
    else
        g_IgnoredLootPlayers.erase(PreferenceKey(player));
}

static void ForgetLootIgnored(Player const* player)
{
    if (!player)
        return;

    std::lock_guard<std::mutex> lock(g_IgnoredLootPlayersMutex);
    g_IgnoredLootPlayers.erase(PreferenceKey(player));
}

static std::vector<Player*> GetEligibleRealPlayers(Player* lootOwner)
{
    std::vector<Player*> players;

    if (!lootOwner)
        return players;

    Group* group = lootOwner->GetGroup();

    if (!group)
    {
        if (!IsPlayerBot(lootOwner) && !IsLootIgnored(lootOwner))
            players.push_back(lootOwner);

        return players;
    }

    for (GroupReference* ref = group->GetFirstMember(); ref; ref = ref->next())
    {
        Player* member = ref->GetSource();

        if (!member || IsPlayerBot(member) || IsLootIgnored(member))
            continue;

        players.push_back(member);
    }

    return players;
}

static Player* SelectRandomEligibleRealPlayer(Player* lootOwner)
{
    std::vector<Player*> players = GetEligibleRealPlayers(lootOwner);

    if (players.empty())
        return nullptr;

    if (players.size() == 1)
        return players.front();

    return players[urand(0, static_cast<uint32>(players.size() - 1))];
}

static ArmorPreference GetPreference(Player const* player)
{
    std::lock_guard<std::mutex> lock(g_PreferencesMutex);
    auto itr = g_Preferences.find(PreferenceKey(player));
    return itr != g_Preferences.end() ? itr->second : ArmorPreference::Auto;
}

static void SetPreference(Player const* player, ArmorPreference pref)
{
    std::lock_guard<std::mutex> lock(g_PreferencesMutex);

    if (pref == ArmorPreference::Auto)
        g_Preferences.erase(PreferenceKey(player));
    else
        g_Preferences[PreferenceKey(player)] = pref;
}

static void ForgetPreference(Player const* player)
{
    std::lock_guard<std::mutex> lock(g_PreferencesMutex);
    g_Preferences.erase(PreferenceKey(player));
}

static char const* PreferenceName(ArmorPreference pref)
{
    switch (pref)
    {
        case ArmorPreference::Auto:    return "Auto";
        case ArmorPreference::Cloth:   return "Cloth / Tissu";
        case ArmorPreference::Leather: return "Leather / Cuir";
        case ArmorPreference::Mail:    return "Mail / Maille";
        case ArmorPreference::Plate:   return "Plate / Plaque";
        case ArmorPreference::Off:     return "Off";
    }

    return "Unknown";
}

static uint32 ArmorSubclassFromPreference(ArmorPreference pref)
{
    switch (pref)
    {
        case ArmorPreference::Cloth:   return ITEM_SUBCLASS_ARMOR_CLOTH;
        case ArmorPreference::Leather: return ITEM_SUBCLASS_ARMOR_LEATHER;
        case ArmorPreference::Mail:    return ITEM_SUBCLASS_ARMOR_MAIL;
        case ArmorPreference::Plate:   return ITEM_SUBCLASS_ARMOR_PLATE;
        default:                       return ITEM_SUBCLASS_ARMOR_CLOTH;
    }
}

static uint32 GetHighestCurrentArmorSubclass(Player const* player)
{
    if (!player)
        return ITEM_SUBCLASS_ARMOR_CLOTH;

    // This uses the player's CURRENT proficiencies, rather than a class-name
    // approximation. It therefore naturally handles the WotLK level-40
    // transitions (Leather->Mail, Mail->Plate) once the skill is learned.
    if (player->HasSkill(SKILL_PLATE_MAIL))
        return ITEM_SUBCLASS_ARMOR_PLATE;

    if (player->HasSkill(SKILL_MAIL))
        return ITEM_SUBCLASS_ARMOR_MAIL;

    if (player->HasSkill(SKILL_LEATHER))
        return ITEM_SUBCLASS_ARMOR_LEATHER;

    return ITEM_SUBCLASS_ARMOR_CLOTH;
}

static uint32 GetDesiredArmorSubclass(Player const* player)
{
    ArmorPreference pref = GetPreference(player);

    if (pref == ArmorPreference::Auto)
        return GetHighestCurrentArmorSubclass(player);

    return ArmorSubclassFromPreference(pref);
}

static bool IsBodyArmor(ItemTemplate const* proto)
{
    if (!proto || proto->Class != ITEM_CLASS_ARMOR)
        return false;

    if (proto->SubClass < ITEM_SUBCLASS_ARMOR_CLOTH ||
        proto->SubClass > ITEM_SUBCLASS_ARMOR_PLATE)
        return false;

    switch (proto->InventoryType)
    {
        case INVTYPE_HEAD:
        case INVTYPE_SHOULDERS:
        case INVTYPE_CHEST:
        case INVTYPE_WAIST:
        case INVTYPE_LEGS:
        case INVTYPE_FEET:
        case INVTYPE_WRISTS:
        case INVTYPE_HANDS:
        case INVTYPE_ROBE:
            return true;
        default:
            return false;
    }
}

static bool IsWeapon(ItemTemplate const* proto)
{
    if (!proto || proto->Class != ITEM_CLASS_WEAPON)
        return false;

    // Never turn combat loot into a fishing pole.
    return proto->SubClass != ITEM_SUBCLASS_WEAPON_FISHING_POLE;
}

static GearCategory GetCategory(ItemTemplate const* proto)
{
    if (IsBodyArmor(proto))
        return GearCategory::Armor;

    if (IsWeapon(proto))
        return GearCategory::Weapon;

    return GearCategory::None;
}

static bool IsUsefulForPlayer(Player* player, ItemTemplate const* proto, GearCategory category)
{
    if (!player || !proto)
        return false;

    if (player->CanUseItem(proto) != EQUIP_ERR_OK)
        return false;

    if (category == GearCategory::Armor)
        return proto->SubClass == GetDesiredArmorSubclass(player);

    if (category == GearCategory::Weapon)
        return true;

    return false;
}

static std::unordered_set<int32> LoadConditionedSourceEntries(uint32 sourceType, uint32 sourceGroup)
{
    std::unordered_set<int32> result;

    QueryResult query = WorldDatabase.Query(
        "SELECT DISTINCT SourceEntry FROM conditions "
        "WHERE SourceTypeOrReferenceId = {} AND SourceGroup = {}",
        sourceType, sourceGroup);

    if (!query)
        return result;

    do
    {
        Field* fields = query->Fetch();
        result.insert(fields[0].Get<int32>());
    }
    while (query->NextRow());

    return result;
}

static void LoadReferenceRows(
    uint32 referenceEntry,
    uint16 inheritedLootMode,
    float inheritedWeight,
    std::unordered_set<uint32>& referenceStack,
    std::vector<Candidate>& out)
{
    if (!referenceEntry || referenceStack.count(referenceEntry))
        return;

    referenceStack.insert(referenceEntry);

    std::unordered_set<int32> conditioned =
        LoadConditionedSourceEntries(CONDITION_SOURCE_TYPE_REFERENCE_LOOT_TEMPLATE, referenceEntry);

    QueryResult query = WorldDatabase.Query(
        "SELECT Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount "
        "FROM reference_loot_template WHERE Entry = {}",
        referenceEntry);

    if (query)
    {
        do
        {
            Field* fields = query->Fetch();

            uint32 itemId = fields[0].Get<uint32>();
            int32 reference = fields[1].Get<int32>();
            float chance = fields[2].Get<float>();
            bool needsQuest = fields[3].Get<bool>();
            uint16 rowLootMode = fields[4].Get<uint16>();
            uint8 groupId = fields[5].Get<uint8>();
            uint8 minCount = fields[6].Get<uint8>();
            uint8 maxCount = fields[7].Get<uint8>();

            if (!rowLootMode)
                rowLootMode = LOOT_MODE_DEFAULT;

            uint16 effectiveMode = inheritedLootMode & rowLootMode;
            if (!effectiveMode)
                continue;

            // If this row has a DB condition, skip it rather than bypassing
            // AzerothCore's condition system when creating the replacement.
            if (conditioned.count(static_cast<int32>(itemId)))
                continue;

            if (reference > 0)
            {
                float refChanceFactor = chance > 0.0f ? (chance / 100.0f) : 1.0f;
                float repeatFactor = maxCount > 0 ? static_cast<float>(maxCount) : 1.0f;

                LoadReferenceRows(
                    static_cast<uint32>(reference),
                    effectiveMode,
                    inheritedWeight * refChanceFactor * repeatFactor,
                    referenceStack,
                    out);

                continue;
            }

            if (!itemId || needsQuest)
                continue;

            Candidate candidate;
            candidate.ItemId = itemId;
            candidate.Weight = inheritedWeight * (chance > 0.0f ? chance : 1.0f);
            candidate.EffectiveLootMode = effectiveMode;
            candidate.GroupId = groupId;
            candidate.MinCount = minCount ? minCount : 1;
            candidate.MaxCount = maxCount >= candidate.MinCount ? maxCount : candidate.MinCount;

            out.push_back(candidate);
        }
        while (query->NextRow());
    }

    referenceStack.erase(referenceEntry);
}

static std::shared_ptr<std::vector<Candidate>> LoadCreaturePool(uint32 lootId)
{
    auto result = std::make_shared<std::vector<Candidate>>();

    std::unordered_set<int32> conditioned =
        LoadConditionedSourceEntries(CONDITION_SOURCE_TYPE_CREATURE_LOOT_TEMPLATE, lootId);

    QueryResult query = WorldDatabase.Query(
        "SELECT Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount "
        "FROM creature_loot_template WHERE Entry = {}",
        lootId);

    if (!query)
        return result;

    std::unordered_set<uint32> referenceStack;

    do
    {
        Field* fields = query->Fetch();

        uint32 itemId = fields[0].Get<uint32>();
        int32 reference = fields[1].Get<int32>();
        float chance = fields[2].Get<float>();
        bool needsQuest = fields[3].Get<bool>();
        uint16 rowLootMode = fields[4].Get<uint16>();
        uint8 groupId = fields[5].Get<uint8>();
        uint8 minCount = fields[6].Get<uint8>();
        uint8 maxCount = fields[7].Get<uint8>();

        if (!rowLootMode)
            rowLootMode = LOOT_MODE_DEFAULT;

        if (conditioned.count(static_cast<int32>(itemId)))
            continue;

        if (reference > 0)
        {
            float refChanceFactor = chance > 0.0f ? (chance / 100.0f) : 1.0f;
            float repeatFactor = maxCount > 0 ? static_cast<float>(maxCount) : 1.0f;

            LoadReferenceRows(
                static_cast<uint32>(reference),
                rowLootMode,
                refChanceFactor * repeatFactor,
                referenceStack,
                *result);

            continue;
        }

        if (!itemId || needsQuest)
            continue;

        Candidate candidate;
        candidate.ItemId = itemId;
        candidate.Weight = chance > 0.0f ? chance : 1.0f;
        candidate.EffectiveLootMode = rowLootMode;
        candidate.GroupId = groupId;
        candidate.MinCount = minCount ? minCount : 1;
        candidate.MaxCount = maxCount >= candidate.MinCount ? maxCount : candidate.MinCount;

        result->push_back(candidate);
    }
    while (query->NextRow());

    return result;
}

static void BuildTemplateMapLocked()
{
    g_TemplateToCreatureLootId.clear();

    QueryResult query = WorldDatabase.Query("SELECT DISTINCT Entry FROM creature_loot_template");

    if (query)
    {
        do
        {
            Field* fields = query->Fetch();
            uint32 entry = fields[0].Get<uint32>();

            if (LootTemplate const* lootTemplate = LootTemplates_Creature.GetLootFor(entry))
                g_TemplateToCreatureLootId[lootTemplate] = entry;
        }
        while (query->NextRow());
    }

    g_TemplateMapBuilt = true;
}

static uint32 GetCreatureLootIdForTemplate(LootTemplate const* lootTemplate)
{
    if (!lootTemplate)
        return 0;

    std::lock_guard<std::mutex> lock(g_CacheMutex);

    if (!g_TemplateMapBuilt)
        BuildTemplateMapLocked();

    auto itr = g_TemplateToCreatureLootId.find(lootTemplate);
    if (itr != g_TemplateToCreatureLootId.end())
        return itr->second;

    // Loot tables can be reloaded by a GM. Rebuild once if the pointer changed.
    BuildTemplateMapLocked();

    itr = g_TemplateToCreatureLootId.find(lootTemplate);
    return itr != g_TemplateToCreatureLootId.end() ? itr->second : 0;
}

static std::shared_ptr<std::vector<Candidate>> GetCandidatePool(uint32 lootId)
{
    std::lock_guard<std::mutex> lock(g_CacheMutex);

    auto itr = g_PoolCache.find(lootId);
    if (itr != g_PoolCache.end())
        return itr->second;

    std::shared_ptr<std::vector<Candidate>> pool = LoadCreaturePool(lootId);
    g_PoolCache[lootId] = pool;
    return pool;
}

static bool LootAlreadyContains(Loot const* loot, uint32 itemId)
{
    if (!loot)
        return false;

    for (LootItem const& item : loot->items)
        if (!item.is_looted && item.itemid == itemId)
            return true;

    return false;
}

static Candidate const* SelectCandidate(
    std::vector<Candidate> const& pool,
    Loot const* loot,
    Player* player,
    GearCategory category,
    uint32 quality,
    uint16 lootMode,
    uint32 excludedItemId)
{
    std::vector<Candidate const*> eligible;
    float totalWeight = 0.0f;

    for (Candidate const& candidate : pool)
    {
        if (candidate.ItemId == excludedItemId)
            continue;

        if (!(candidate.EffectiveLootMode & lootMode))
            continue;

        if (LootAlreadyContains(loot, candidate.ItemId))
            continue;

        ItemTemplate const* proto = sObjectMgr->GetItemTemplate(candidate.ItemId);
        if (!proto || proto->Quality != quality)
            continue;

        if (GetCategory(proto) != category)
            continue;

        if (!IsUsefulForPlayer(player, proto, category))
            continue;

        float weight = candidate.Weight > 0.0f ? candidate.Weight : 1.0f;
        eligible.push_back(&candidate);
        totalWeight += weight;
    }

    if (eligible.empty())
        return nullptr;

    if (eligible.size() == 1 || totalWeight <= 0.0f)
        return eligible.front();

    float roll = frand(0.0f, totalWeight);

    for (Candidate const* candidate : eligible)
    {
        roll -= candidate->Weight > 0.0f ? candidate->Weight : 1.0f;
        if (roll <= 0.0f)
            return candidate;
    }

    return eligible.back();
}

static Candidate const* SelectBestLowerQualityCandidate(
    std::vector<Candidate> const& pool,
    Loot const* loot,
    Player* player,
    GearCategory category,
    uint32 originalQuality,
    uint16 lootMode,
    uint32 excludedItemId)
{
    if (originalQuality <= g_Config.MinQuality)
        return nullptr;

    // Prefer the closest lower rarity:
    // Epic -> Rare -> Uncommon, Rare -> Uncommon, etc.
    for (int32 quality = static_cast<int32>(originalQuality) - 1;
         quality >= static_cast<int32>(g_Config.MinQuality);
         --quality)
    {
        if (Candidate const* candidate = SelectCandidate(
                pool,
                loot,
                player,
                category,
                static_cast<uint32>(quality),
                lootMode,
                excludedItemId))
        {
            return candidate;
        }
    }

    return nullptr;
}

static LootStoreItem MakeLootStoreItem(Candidate const& candidate)
{
    // Equippable loot should be a single item. Preserve the source GroupId and
    // loot mode, but force a count of 1 for a reroll/bonus to avoid accidental
    // multi-count equipment from unusual custom tables.
    return LootStoreItem(
        candidate.ItemId,
        0,
        100.0f,
        false,
        candidate.EffectiveLootMode ? candidate.EffectiveLootMode : LOOT_MODE_DEFAULT,
        candidate.GroupId,
        1,
        1);
}

static bool ReplaceLootItem(Loot* loot, size_t index, Candidate const& candidate)
{
    if (!loot || index >= loot->items.size())
        return false;

    size_t before = loot->items.size();
    uint32 originalIndex = loot->items[index].itemIndex;

    LootStoreItem generatedFrom = MakeLootStoreItem(candidate);
    loot->AddItem(generatedFrom);

    if (loot->items.size() != before + 1)
        return false;

    LootItem replacement = std::move(loot->items.back());
    loot->items.pop_back();

    replacement.itemIndex = originalIndex;
    loot->items[index] = std::move(replacement);
    return true;
}

static bool AddBonusItem(Loot* loot, Candidate const& candidate)
{
    if (!loot || loot->items.size() >= MAX_NR_LOOT_ITEMS)
        return false;

    size_t before = loot->items.size();

    LootStoreItem generatedFrom = MakeLootStoreItem(candidate);
    loot->AddItem(generatedFrom);

    return loot->items.size() == before + 1;
}


static char const* ItemQualityColor(uint32 quality)
{
    switch (quality)
    {
        case ITEM_QUALITY_POOR:      return "ff9d9d9d";
        case ITEM_QUALITY_NORMAL:    return "ffffffff";
        case ITEM_QUALITY_UNCOMMON:  return "ff1eff00";
        case ITEM_QUALITY_RARE:      return "ff0070dd";
        case ITEM_QUALITY_EPIC:      return "ffa335ee";
        case ITEM_QUALITY_LEGENDARY: return "ffff8000";
        case ITEM_QUALITY_ARTIFACT:  return "ffe6cc80";
        case ITEM_QUALITY_HEIRLOOM:  return "ffe6cc80";
        default:                     return "ffffffff";
    }
}

static std::string MakeItemLink(uint32 itemId)
{
    ItemTemplate const* proto = sObjectMgr->GetItemTemplate(itemId);
    if (!proto)
        return "[item:" + std::to_string(itemId) + "]";

    return "|c" + std::string(ItemQualityColor(proto->Quality)) +
        "|Hitem:" + std::to_string(itemId) +
        ":0:0:0:0:0:0:0|h[" + proto->Name1 + "]|h|r";
}

static uint32 RegisterSubstitution(
    Player* player,
    SubstitutionKind kind,
    uint32 originalItemId,
    int32 originalRandomPropertyId,
    uint32 substituteItemId)
{
    if (!player)
        return 0;

    uint32 id = g_NextSubstitutionId.fetch_add(1);
    if (id == 0)
        id = g_NextSubstitutionId.fetch_add(1);

    SubstitutionRecord record;
    record.Id = id;
    record.PlayerGuid = PreferenceKey(player);
    record.Kind = kind;
    record.OriginalItemId = originalItemId;
    record.OriginalRandomPropertyId = originalRandomPropertyId;
    record.SubstituteItemId = substituteItemId;

    {
        std::lock_guard<std::mutex> lock(g_SubstitutionMutex);
        auto& history = g_SubstitutionHistory[record.PlayerGuid];
        history.push_back(record);

        uint32 maxRecords = std::max<uint32>(1, g_Config.MaxUndoRecordsPerCharacter);
        while (history.size() > maxRecords)
            history.pop_front();
    }

    return id;
}

static void NotifyReplacement(
    Player* player,
    uint32 id,
    uint32 originalItemId,
    uint32 substituteItemId)
{
    if (!g_Config.NotifySubstitutions || !player || !player->GetSession())
        return;

    ChatHandler handler(player->GetSession());
    std::string message =
        "|cff00ff96[SmartLoot #" + std::to_string(id) + "]|r " +
        MakeItemLink(originalItemId) + " |cffffffff->|r " +
        MakeItemLink(substituteItemId) +
        " |cffaaaaaa(annuler: .subundo " + std::to_string(id) + ")|r";

    handler.SendSysMessage(message);
}

static void NotifyBonus(
    Player* player,
    uint32 id,
    uint32 originalItemId,
    uint32 bonusItemId)
{
    if (!g_Config.NotifySubstitutions || !player || !player->GetSession())
        return;

    ChatHandler handler(player->GetSession());
    std::string message =
        "|cff00ff96[SmartLoot #" + std::to_string(id) + "]|r " +
        MakeItemLink(originalItemId) +
        " |cffffd100conserve; bonus de substitution:|r " +
        MakeItemLink(bonusItemId) +
        " |cffaaaaaa(annuler le bonus: .subundo " + std::to_string(id) + ")|r";

    handler.SendSysMessage(message);
}

static SubstitutionRecord* FindSubstitutionRecordLocked(uint64 playerGuid, uint32 id)
{
    auto historyItr = g_SubstitutionHistory.find(playerGuid);
    if (historyItr == g_SubstitutionHistory.end())
        return nullptr;

    for (SubstitutionRecord& record : historyItr->second)
        if (record.Id == id)
            return &record;

    return nullptr;
}

static std::string ToLower(std::string value)
{
    std::transform(value.begin(), value.end(), value.begin(),
        [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return value;
}

static std::string Trim(std::string value)
{
    auto notSpace = [](unsigned char c) { return !std::isspace(c); };

    value.erase(value.begin(), std::find_if(value.begin(), value.end(), notSpace));
    value.erase(std::find_if(value.rbegin(), value.rend(), notSpace).base(), value.end());

    return value;
}

static std::string CurrentModeDescription(Player* player)
{
    ArmorPreference pref = GetPreference(player);

    std::string result = "Smart loot mode: ";
    result += PreferenceName(pref);

    if (pref == ArmorPreference::Auto)
    {
        result += " (current armor target: ";

        switch (GetHighestCurrentArmorSubclass(player))
        {
            case ITEM_SUBCLASS_ARMOR_PLATE:   result += "Plate / Plaque"; break;
            case ITEM_SUBCLASS_ARMOR_MAIL:    result += "Mail / Maille"; break;
            case ITEM_SUBCLASS_ARMOR_LEATHER: result += "Leather / Cuir"; break;
            default:                          result += "Cloth / Tissu"; break;
        }

        result += ")";
    }

    return result;
}

class SoloLootRerollMiscScript : public MiscScript
{
public:
    SoloLootRerollMiscScript()
        : MiscScript("SoloLootRerollMiscScript", { MISCHOOK_ON_AFTER_LOOT_TEMPLATE_PROCESS })
    {
    }

    void OnAfterLootTemplateProcess(
        Loot* loot,
        LootTemplate const* lootTemplate,
        LootStore const& store,
        Player* lootOwner,
        bool /*personal*/,
        bool /*noEmptyError*/,
        uint16 lootMode) override
    {
        if (!g_Config.Enable || !loot || !lootOwner)
            return;

        // This module intentionally operates only on normal creature/boss loot.
        if (&store != &LootTemplates_Creature)
            return;

        // One or many real players are supported. The module chooses one
        // eligible real player uniformly at random for THIS loot generation.
        // Players using ".lootignore on" are removed from the candidate set.
        Player* realPlayer = SelectRandomEligibleRealPlayer(lootOwner);
        if (!realPlayer)
            return;

        ArmorPreference pref = GetPreference(realPlayer);
        if (pref == ArmorPreference::Off)
            return;

        uint32 lootId = GetCreatureLootIdForTemplate(lootTemplate);
        if (!lootId)
            return;

        std::shared_ptr<std::vector<Candidate>> pool = GetCandidatePool(lootId);
        if (!pool || pool->empty())
            return;

        // Only process the items that existed when the normal loot generation
        // finished. Bonus items appended by this module are not recursively
        // reconsidered.
        size_t originalItemCount = loot->items.size();

        for (size_t i = 0; i < originalItemCount && i < loot->items.size(); ++i)
        {
            LootItem const& originalLootItem = loot->items[i];

            if (originalLootItem.is_looted ||
                originalLootItem.needs_quest ||
                !originalLootItem.conditions.empty())
                continue;

            ItemTemplate const* originalProto =
                sObjectMgr->GetItemTemplate(originalLootItem.itemid);

            if (!originalProto || originalProto->Quality < g_Config.MinQuality)
                continue;

            GearCategory category = GetCategory(originalProto);

            if (category == GearCategory::Armor && !g_Config.EnableArmor)
                continue;

            if (category == GearCategory::Weapon && !g_Config.EnableWeapons)
                continue;

            if (category == GearCategory::None)
                continue;

            if (IsUsefulForPlayer(realPlayer, originalProto, category))
                continue;

            uint32 originalItemId = originalLootItem.itemid;
            uint32 quality = originalProto->Quality;

            // Green: replace with another usable green from the same reachable
            // creature loot pool. Slot does NOT have to match.
            if (quality == ITEM_QUALITY_UNCOMMON && g_Config.ReplaceUncommon)
            {
                if (Candidate const* replacement = SelectCandidate(
                        *pool,
                        loot,
                        realPlayer,
                        category,
                        ITEM_QUALITY_UNCOMMON,
                        lootMode,
                        originalItemId))
                {
                    int32 originalRandomPropertyId = loot->items[i].randomPropertyId;

                    if (ReplaceLootItem(loot, i, *replacement))
                    {
                        uint32 substitutionId = RegisterSubstitution(
                            realPlayer,
                            SubstitutionKind::Replacement,
                            originalItemId,
                            originalRandomPropertyId,
                            replacement->ItemId);

                        NotifyReplacement(
                            realPlayer,
                            substitutionId,
                            originalItemId,
                            replacement->ItemId);

                        if (g_Config.Debug)
                        {
                            LOG_INFO(
                                "module",
                                "[mod-solo-loot-reroll] {}: SmartLoot #{} replaced green item {} with {} (lootId {})",
                                realPlayer->GetName(), substitutionId, originalItemId, replacement->ItemId, lootId);
                        }
                    }
                }

                continue;
            }

            if (quality < ITEM_QUALITY_RARE)
                continue;

            // Rare+ (blue/epic/legendary...):
            // 1) first try to replace with a usable item of THE SAME QUALITY;
            // 2) if none exists, keep the original item and append the highest
            //    lower-quality compatible item available in the same loot pool.
            if (g_Config.ReplaceRareOrHigher)
            {
                if (Candidate const* replacement = SelectCandidate(
                        *pool,
                        loot,
                        realPlayer,
                        category,
                        quality,
                        lootMode,
                        originalItemId))
                {
                    int32 originalRandomPropertyId = loot->items[i].randomPropertyId;

                    if (ReplaceLootItem(loot, i, *replacement))
                    {
                        uint32 substitutionId = RegisterSubstitution(
                            realPlayer,
                            SubstitutionKind::Replacement,
                            originalItemId,
                            originalRandomPropertyId,
                            replacement->ItemId);

                        NotifyReplacement(
                            realPlayer,
                            substitutionId,
                            originalItemId,
                            replacement->ItemId);

                        if (g_Config.Debug)
                        {
                            LOG_INFO(
                                "module",
                                "[mod-solo-loot-reroll] {}: SmartLoot #{} replaced item {} with same-quality item {} (quality {}, lootId {})",
                                realPlayer->GetName(), substitutionId, originalItemId, replacement->ItemId, quality, lootId);
                        }

                        continue;
                    }
                }
            }

            if (g_Config.LowerQualityFallbackBonus &&
                loot->items.size() < MAX_NR_LOOT_ITEMS)
            {
                if (Candidate const* bonus = SelectBestLowerQualityCandidate(
                        *pool,
                        loot,
                        realPlayer,
                        category,
                        quality,
                        lootMode,
                        originalItemId))
                {
                    ItemTemplate const* bonusProto = sObjectMgr->GetItemTemplate(bonus->ItemId);

                    if (AddBonusItem(loot, *bonus))
                    {
                        uint32 substitutionId = RegisterSubstitution(
                            realPlayer,
                            SubstitutionKind::Bonus,
                            originalItemId,
                            originalLootItem.randomPropertyId,
                            bonus->ItemId);

                        NotifyBonus(
                            realPlayer,
                            substitutionId,
                            originalItemId,
                            bonus->ItemId);

                        if (g_Config.Debug)
                        {
                            LOG_INFO(
                                "module",
                                "[mod-solo-loot-reroll] {}: SmartLoot #{} kept item {} (quality {}) and added lower-quality bonus {} (quality {}, lootId {})",
                                realPlayer->GetName(),
                                substitutionId,
                                originalItemId,
                                quality,
                                bonus->ItemId,
                                bonusProto ? bonusProto->Quality : 0,
                                lootId);
                        }
                    }
                }
            }
        }
    }
};

class SoloLootRerollPlayerScript : public PlayerScript
{
public:
    SoloLootRerollPlayerScript()
        : PlayerScript("SoloLootRerollPlayerScript", { PLAYERHOOK_ON_LOGOUT })
    {
    }

    void OnPlayerLogout(Player* player) override
    {
        ForgetPreference(player);
        ForgetLootIgnored(player);
    }
};

class SoloLootRerollWorldScript : public WorldScript
{
public:
    SoloLootRerollWorldScript() : WorldScript("SoloLootRerollWorldScript") {}

    void OnBeforeConfigLoad(bool /*reload*/) override
    {
        g_Config.Enable =
            sConfigMgr->GetOption<bool>("SoloLootReroll.Enable", true);

        g_Config.EnableArmor =
            sConfigMgr->GetOption<bool>("SoloLootReroll.EnableArmor", true);

        g_Config.EnableWeapons =
            sConfigMgr->GetOption<bool>("SoloLootReroll.EnableWeapons", true);

        g_Config.MinQuality =
            sConfigMgr->GetOption<uint32>("SoloLootReroll.MinQuality", ITEM_QUALITY_UNCOMMON);

        if (g_Config.MinQuality < ITEM_QUALITY_UNCOMMON)
            g_Config.MinQuality = ITEM_QUALITY_UNCOMMON;

        g_Config.ReplaceUncommon =
            sConfigMgr->GetOption<bool>("SoloLootReroll.ReplaceUncommon", true);

        g_Config.ReplaceRareOrHigher =
            sConfigMgr->GetOption<bool>("SoloLootReroll.ReplaceRareOrHigher", true);

        g_Config.LowerQualityFallbackBonus =
            sConfigMgr->GetOption<bool>("SoloLootReroll.LowerQualityFallbackBonus", true);

        g_Config.NotifySubstitutions =
            sConfigMgr->GetOption<bool>("SoloLootReroll.NotifySubstitutions", true);

        g_Config.MaxUndoRecordsPerCharacter =
            sConfigMgr->GetOption<uint32>("SoloLootReroll.MaxUndoRecordsPerCharacter", 100);

        if (!g_Config.MaxUndoRecordsPerCharacter)
            g_Config.MaxUndoRecordsPerCharacter = 1;

        g_Config.Debug =
            sConfigMgr->GetOption<bool>("SoloLootReroll.Debug", false);

        {
            std::lock_guard<std::mutex> lock(g_CacheMutex);
            g_PoolCache.clear();
            g_TemplateToCreatureLootId.clear();
            g_TemplateMapBuilt = false;
        }

        LOG_INFO("module", "[mod-solo-loot-reroll] {}", g_Config.Enable ? "Enabled" : "Disabled");
        LOG_INFO("module", "[mod-solo-loot-reroll] Armor: {}", g_Config.EnableArmor ? "true" : "false");
        LOG_INFO("module", "[mod-solo-loot-reroll] Weapons: {}", g_Config.EnableWeapons ? "true" : "false");
        LOG_INFO("module", "[mod-solo-loot-reroll] MinQuality: {}", g_Config.MinQuality);
        LOG_INFO("module", "[mod-solo-loot-reroll] ReplaceUncommon: {}", g_Config.ReplaceUncommon ? "true" : "false");
        LOG_INFO("module", "[mod-solo-loot-reroll] ReplaceRareOrHigher: {}", g_Config.ReplaceRareOrHigher ? "true" : "false");
        LOG_INFO("module", "[mod-solo-loot-reroll] LowerQualityFallbackBonus: {}", g_Config.LowerQualityFallbackBonus ? "true" : "false");
        LOG_INFO("module", "[mod-solo-loot-reroll] NotifySubstitutions: {}", g_Config.NotifySubstitutions ? "true" : "false");
        LOG_INFO("module", "[mod-solo-loot-reroll] MaxUndoRecordsPerCharacter: {}", g_Config.MaxUndoRecordsPerCharacter);
        LOG_INFO("module", "[mod-solo-loot-reroll] Default player mode: Auto (no custom persistence table)");
    }
};

class SoloLootRerollCommandScript : public CommandScript
{
public:
    SoloLootRerollCommandScript() : CommandScript("SoloLootRerollCommandScript") {}

    ChatCommandTable GetCommands() const override
    {
        static ChatCommandTable commandTable =
        {
            { "loottypeset", HandleLootTypeSet, SEC_PLAYER, Console::No },
            { "loottype",    HandleLootTypeInfo, SEC_PLAYER, Console::No },
            { "lootignore",  HandleLootIgnore, SEC_PLAYER, Console::No },
            { "subundo",     HandleSubUndo, SEC_PLAYER, Console::No }
        };

        return commandTable;
    }

    static bool HandleLootIgnore(ChatHandler* handler, char const* args)
    {
        Player* player = handler->GetPlayer();
        if (!player)
            return false;

        std::string value = ToLower(Trim(args ? args : ""));

        if (value.empty() || value == "status")
        {
            handler->PSendSysMessage(
                "SmartLoot selection: {}.",
                IsLootIgnored(player)
                    ? "IGNORED - vous ne serez pas choisi comme cible de substitution"
                    : "ELIGIBLE - vous pouvez etre choisi comme cible de substitution");

            handler->SendSysMessage(
                "Usage: .lootignore on|off  (alias logique: on = m'ignorer, off = me reprendre)");
            return true;
        }

        if (value == "on" || value == "1" || value == "yes" ||
            value == "oui" || value == "ignore" || value == "ignored")
        {
            SetLootIgnored(player, true);
            handler->SendSysMessage(
                "SmartLoot: vous etes maintenant ignore pour les substitutions. Les autres joueurs eligibles seront favorises.");
            return true;
        }

        if (value == "off" || value == "0" || value == "no" ||
            value == "non" || value == "enable" || value == "eligible")
        {
            SetLootIgnored(player, false);
            handler->SendSysMessage(
                "SmartLoot: vous etes de nouveau eligible pour les substitutions.");
            return true;
        }

        handler->SendSysMessage("Usage: .lootignore on|off|status");
        return false;
    }

    static bool HandleSubUndo(ChatHandler* handler, char const* args)
    {
        Player* player = handler->GetPlayer();
        if (!player)
            return false;

        std::string value = Trim(args ? args : "");
        if (value.empty())
        {
            handler->SendSysMessage("Usage: .subundo <id>");
            return false;
        }

        uint32 id = 0;
        try
        {
            size_t parsed = 0;
            unsigned long parsedId = std::stoul(value, &parsed, 10);
            if (parsed != value.size() || parsedId == 0 || parsedId > UINT32_MAX)
                throw std::invalid_argument("bad id");

            id = static_cast<uint32>(parsedId);
        }
        catch (...)
        {
            handler->SendSysMessage("ID invalide. Usage: .subundo <id>");
            return false;
        }

        SubstitutionRecord snapshot;

        {
            std::lock_guard<std::mutex> lock(g_SubstitutionMutex);
            SubstitutionRecord* record = FindSubstitutionRecordLocked(PreferenceKey(player), id);

            if (!record)
            {
                handler->PSendSysMessage(
                    "SmartLoot #{} introuvable (mauvais personnage, historique expire ou redemarrage serveur).",
                    id);
                return false;
            }

            if (record->Undone)
            {
                handler->PSendSysMessage("SmartLoot #{} a deja ete annule.", id);
                return false;
            }

            snapshot = *record;
        }

        // The substituted/bonus item must really be owned by THIS character.
        // inBankAlso=false intentionally does not accept an item sitting in the bank.
        if (!player->HasItemCount(snapshot.SubstituteItemId, 1, false))
        {
            std::string message =
                "Impossible d'annuler SmartLoot #" + std::to_string(id) +
                ": " + MakeItemLink(snapshot.SubstituteItemId) +
                " n'est pas dans votre inventaire/equipement.";
            handler->SendSysMessage(message);
            return false;
        }

        if (snapshot.Kind == SubstitutionKind::Bonus)
        {
            player->DestroyItemCount(snapshot.SubstituteItemId, 1, true);

            {
                std::lock_guard<std::mutex> lock(g_SubstitutionMutex);
                if (SubstitutionRecord* record = FindSubstitutionRecordLocked(PreferenceKey(player), id))
                    record->Undone = true;
            }

            std::string message =
                "|cff00ff96[SmartLoot #" + std::to_string(id) +
                "]|r bonus annule: " + MakeItemLink(snapshot.SubstituteItemId) +
                " retire. Le drop original " + MakeItemLink(snapshot.OriginalItemId) +
                " reste inchange.";
            handler->SendSysMessage(message);
            return true;
        }

        // Replacement undo is transactional from the player's point of view:
        // first ensure the original item FITS, then remove the substitute.
        ItemPosCountVec dest;
        InventoryResult canStore =
            player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, snapshot.OriginalItemId, 1);

        if (canStore != EQUIP_ERR_OK)
        {
            std::string message =
                "Impossible d'annuler SmartLoot #" + std::to_string(id) +
                ": pas de place pour restaurer " + MakeItemLink(snapshot.OriginalItemId) +
                ". Aucun objet n'a ete retire.";
            handler->SendSysMessage(message);
            return false;
        }

        player->DestroyItemCount(snapshot.SubstituteItemId, 1, true);

        Item* restored = player->StoreNewItem(
            dest,
            snapshot.OriginalItemId,
            true,
            snapshot.OriginalRandomPropertyId);

        if (!restored)
        {
            // Extremely defensive rollback: if the core unexpectedly refuses the
            // original after CanStoreNewItem succeeded, restore the substitute.
            player->StoreNewItemInBestSlots(snapshot.SubstituteItemId, 1);

            handler->PSendSysMessage(
                "Echec inattendu de SmartLoot #{}: substitution restauree, aucune perte volontaire.",
                id);
            return false;
        }

        {
            std::lock_guard<std::mutex> lock(g_SubstitutionMutex);
            if (SubstitutionRecord* record = FindSubstitutionRecordLocked(PreferenceKey(player), id))
                record->Undone = true;
        }

        std::string message =
            "|cff00ff96[SmartLoot #" + std::to_string(id) + "]|r annule: " +
            MakeItemLink(snapshot.SubstituteItemId) + " |cffffffff->|r " +
            MakeItemLink(snapshot.OriginalItemId) + ".";
        handler->SendSysMessage(message);

        return true;
    }

    static bool HandleLootTypeInfo(ChatHandler* handler, char const* /*args*/)
    {
        Player* player = handler->GetPlayer();
        if (!player)
            return false;

        std::string message = CurrentModeDescription(player);
        handler->SendSysMessage(message.c_str());

        Group* group = player->GetGroup();
        uint32 realPlayers = 0;
        uint32 eligibleRealPlayers = 0;
        uint32 ignoredRealPlayers = 0;
        uint32 bots = 0;

        auto countMember = [&](Player* member)
        {
            if (!member)
                return;

            if (IsPlayerBot(member))
            {
                ++bots;
                return;
            }

            ++realPlayers;

            if (IsLootIgnored(member))
                ++ignoredRealPlayers;
            else
                ++eligibleRealPlayers;
        };

        if (!group)
            countMember(player);
        else
            for (GroupReference* ref = group->GetFirstMember(); ref; ref = ref->next())
                countMember(ref->GetSource());

        handler->SendSysMessage(
            eligibleRealPlayers > 0
                ? "SmartLoot group condition: active. One eligible real player is chosen randomly for each generated creature loot."
                : "SmartLoot group condition: inactive. No eligible real player is available.");

        std::string counts =
            "Online group members: " + std::to_string(realPlayers) +
            " real player(s) (" + std::to_string(eligibleRealPlayers) +
            " eligible, " + std::to_string(ignoredRealPlayers) +
            " ignored), " + std::to_string(bots) + " PlayerBot(s).";
        handler->SendSysMessage(counts.c_str());

        handler->PSendSysMessage(
            "Your SmartLoot selection state: {}.",
            IsLootIgnored(player) ? "IGNORED" : "ELIGIBLE");

        handler->SendSysMessage(
            "Weapons: automatic; an unusable weapon may be rerolled/compensated with a weapon the randomly selected player can use.");

        return true;
    }

    static bool HandleLootTypeSet(ChatHandler* handler, char const* args)
    {
        Player* player = handler->GetPlayer();
        if (!player)
            return false;

        std::string value = ToLower(Trim(args ? args : ""));

        if (value.empty() || value == "status")
            return HandleLootTypeInfo(handler, "");

        ArmorPreference pref;

        if (value == "auto" || value == "automatic" || value == "automatique" || value == "reset")
            pref = ArmorPreference::Auto;
        else if (value == "off" || value == "none" || value == "disable" || value == "desactive")
            pref = ArmorPreference::Off;
        else if (value == "cloth" || value == "tissu")
            pref = ArmorPreference::Cloth;
        else if (value == "leather" || value == "cuir")
            pref = ArmorPreference::Leather;
        else if (value == "mail" || value == "maille")
            pref = ArmorPreference::Mail;
        else if (value == "plate" || value == "plaque")
            pref = ArmorPreference::Plate;
        else
        {
            handler->SendSysMessage(
                "Usage: .loottypeset auto|off|tissu|cloth|cuir|leather|maille|mail|plaque|plate");
            return false;
        }

        SetPreference(player, pref);

        std::string message = "Smart loot preference set to: ";
        message += PreferenceName(pref);
        handler->SendSysMessage(message.c_str());

        if (pref == ArmorPreference::Auto)
        {
            std::string autoMessage = CurrentModeDescription(player);
            handler->SendSysMessage(autoMessage.c_str());
        }
        else if (pref == ArmorPreference::Off)
        {
            handler->SendSysMessage(
                "Smart reroll is disabled for this character until relog/restart or '.loottypeset auto'.");
        }

        return true;
    }
};

} // namespace SoloLootReroll

void AddSC_mod_solo_loot_reroll()
{
    new SoloLootReroll::SoloLootRerollMiscScript();
    new SoloLootReroll::SoloLootRerollPlayerScript();
    new SoloLootReroll::SoloLootRerollWorldScript();
    new SoloLootReroll::SoloLootRerollCommandScript();
}
